server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/monyormsdb
    username: postgres
    password: "0504"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
auth-service:
  url: http://localhost:9090
logging:
  level:
    com.example.monyorms.filter: DEBUG